- hosts: "{{ target }}"
  sudo: True
  vars:
    java_packages:
      - oracle-java8-installer
  roles:
    - smola.java

  tasks:

  - name: install missing package if needed
    apt: name={{ item }} update_cache=yes
    with_items:
      - curl
      - apt-transport-https
      - python-software-properties

  - name: add crate repository
    apt_repository: repo="ppa:crate/stable" state=present update_cache=yes
    
  - name: Install crate.io packages
    apt: name={{ item }} update_cache=yes
    with_items:
      - crate

  - name: move template to config dir
    template: src=/tmp/crate.yml.j2 
              dest=/etc/crate/crate.yml 
              force=yes 
              mode="u=rw,g=r,o=r"

  - name: start/restart service
    service: name=crate state=restarted